// <auto-generated />
namespace CinemaTicketSystem.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class orderinit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(orderinit));
        
        string IMigrationMetadata.Id
        {
            get { return "201805271104561_order init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
