// <auto-generated />
namespace CinemaTicketSystem.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class orderupdates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(orderupdates));
        
        string IMigrationMetadata.Id
        {
            get { return "201806031122443_order updates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
