// <auto-generated />
namespace CinemaTicketSystem.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class ExpandShowing : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ExpandShowing));
        
        string IMigrationMetadata.Id
        {
            get { return "201805241451029_ExpandShowing"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
